apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: dev
spec:
  type: LoadBalancer   # <--- change from ClusterIP to LoadBalancer
  selector:
    app: frontend-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
