apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
  namespace: staging
  labels:
    app: backend
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      color: green
  template:
    metadata:
      labels:
        app: backend
        color: green
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/useful-variety-470306-n5/gke-repo/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "StrongPass123"
        - name: DB_NAME
          value: "mysql"
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "3306"
